app = "eng-gruposbf-backend-javascript"

[build]
  builder = "heroku/buildpacks:20"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[env]
  PORT = "8080"
  NODE_ENV = "prod"
  LOG_LEVEL = "info"
  CACHE_TIME = "240"
  URL = "https://eng-gruposbf-backend-javascript.fly.dev"