name: master

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: Install Dependencies
        run: npm install

      - name: Lint Stage
        run: npm run lint

      - name: Test Stage
        run: npm run test
  
  deploy:
    needs: test
    name: Deploy App to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only